name: Scala CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Configure git
      run: "git config --global core.autocrlf false"
      shell: bash
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v11
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: target/scala-3.2.2/scoverage-report
    - name: Print coverage
      shell: bash
      run: sbt coverageReport
